### ISSUE TITLE
Normal distribution :  Put confidence interval in the same units as in literature

### ISSUE THREAD

**Issue by deborahduong** [singnet/covid-simulation#46]
a 95% confidence interval is used in this paper and used with the normal _ci routines as is.

https://docs.google.com/document/d/1imCNXOyoyecfD_sVNmKpmbWVB6xqP-FWlHELAyOg1Vs/edit 

Please correct definition of normal distribution.  Now it has:

stdev = ci_upper - mean

this is not the correct mapping of the confidence interval to the stdev

**Comment by deborahduong** [comment]
assigned to @andre-senna by @pennachin at 8/4 meeting

**Comment by deborahduong** [comment]
I mentioned this as a good way to do the conversion in an 8/5 slack conversation with @andre-senna :  https://handbook-5-1.cochrane.org/chapter_7/7_7_3_2_obtaining_standard_deviations_from_standard_errors_and.htm

**Comment by andre-senna** [comment]
Implemented as suggested but I couldn't figure out the N to be used in the CIs provided in https://docs.google.com/document/d/1imCNXOyoyecfD_sVNmKpmbWVB6xqP-FWlHELAyOg1Vs/edit
