### ISSUE TITLE
Use confidence interval calculation with multiple runs in the intelligent agent framework

### ISSUE THREAD

**Issue by deborahduong** [singnet/covid-simulation#52]
The intelligent agent framework already has a way to calculate the confidence interval in multiple runs .  Multiple runs are needed because you have high variance between runs. This can wait for integration with the intelligent agent framework. 

To show why multiple runs are needed, I turned off the part where risk tolerance gradually changed, and ran scenario 5 twice  with risk_tolerance at mean 1 stdev 0 and then twice at mean 0.1 stdev 0.0.  One of the curves at .1 is higher than one of the curves at 1.0.  We can not see the responsiveness of the parameters without multiple runs.  Here are the screenshots:
 https://docs.google.com/document/d/1j6zOHuUdlylbJK2d6Kk3eNc0hPO8s_GZBN4nFDn325I/edit

**Comment by deborahduong** [comment]
I would like to perform the integration

**Comment by andre-senna** [comment]
I'm not sure I understood this issue. Do you want to have support in the basic notebook to perform multiples simulation and compute confidence intervals?

**Comment by deborahduong** [comment]
yes, but I want to use my previous code to do this, as it is already part of the intelligent agent framework, which I will clean and present to you as one of my next tasks.

**Comment by pennachin** [comment]
I think there's two issues here. First is simplifying the mechanics of running many runs with different random seeds. @andre-senna should fix that ASAP. Second is computing stats on the results of many runs. This isn't just confidence intervals, we need plotting to see if there's outliers so we can dig into those if needed, etc. This can evolve as people play with the simulations.

**Comment by deborahduong** [comment]
If you just want simplified repeated runs that are plotted,  the Petronio notebook has those, and I bet they can easily be put in @andre-senna 's notebook.  My framework is best for repeated runs and changing parameters in a json parameter file.

**Comment by deborahduong** [comment]
@andre-senna I would like to present to you my general framework, which works outside the context of a notebook, so we can have a single clean and easy to use codebase.

**Comment by deborahduong** [comment]
simple code assigned to debbie by ben slack converasation 8/15

**Comment by deborahduong** [comment]
resolved 8/12, in pull request
