### ISSUE TITLE
simulation results are not sensitive to risk_tolerance

### ISSUE THREAD

**Issue by deborahduong** [singnet/covid-simulation#57]
In baseline simulation (before PR for issues 48 and 49 are added) the values of risk_tolerance do not make a difference to the simulation result (screenshots: https://docs.google.com/document/d/1j6zOHuUdlylbJK2d6Kk3eNc0hPO8s_GZBN4nFDn325I/edit) .  With 48 and 49 added, internal inspection shows that decisions are being made correctly (more risk tolerance means accepting invitations, making invitations, breaking lockdown at work ) , but it does not show up in the results , either with or without the code for issues 48 and 49.

**Comment by deborahduong** [comment]
Assigned to Debbie by Cassio at weekly meeting

**Comment by deborahduong** [comment]
https://github.com/deborahduong/covid-simulation/blob/master/covid19_sir/Simulation.ipynb shows the same thing in the notebook , run 30 times, as follows:


It looks like risk tolerance changes dont make a difference in any scenario.  scenarios 4 and 5 are effects of propaganda on the scenario of 3, and 7 is effect of propaganda on scenario of 6, and none made a difference in their respective.  but 6 is a fuller lift of lockdown than 3, and as you see they have are right in comparison with each other and with 1.  so I think the risk tolerance is broken.  Although these are normal simulation parameters, risk tolerance had no effect at the extremes when I put them at extremes last week, either. 

scenario 3 lift school lockdowns
stats on infected:
data: [0.018, 0.01, 0.149, 0.028942115768463075, 0.17, 0.046, 0.194, 0.194, 0.23, 0.197, 0.023, 0.012, 0.02, 0.009, 0.038, 0.201, 0.05189620758483034, 0.029, 0.021, 0.11, 0.012, 0.308, 0.1008991008991009, 0.025974025974025976, 0.301, 0.068, 0.132, 0.216, 0.012, 0.149]
min:
0.009
max:
0.308
std:
0.09174397275072574
mean:
0.10255704834088068
median:
0.05994810379241517
95% confidence interval for the mean:
(0.06771364070585179,0.13740045597590958)
using peak of time series:

scenario 4
using peak of time series:
stats on infected:
data: [0.038, 0.158, 0.035, 0.215, 0.313, 0.263, 0.06993006993006994, 0.058, 0.136, 0.282, 0.095, 0.025, 0.011, 0.1415752741774676, 0.186, 0.077, 0.264, 0.012987012987012988, 0.02, 0.137, 0.0946215139442231, 0.036, 0.314, 0.037, 0.121, 0.018, 0.014, 0.1942231075697211, 0.063, 0.205]
min:
0.011
max:
0.314
std:
0.09582190182096621
mean:
0.12114456595361649
median:
0.09481075697211155
95% confidence interval for the mean:
(0.0847524032272075,0.15753672868002547)

scenario 5
using peak of time series:
stats on infected:
data: [0.132, 0.295, 0.079, 0.006993006993006993, 0.285, 0.204, 0.144, 0.024, 0.103, 0.21078921078921078, 0.042, 0.017, 0.2904191616766467, 0.157, 0.07, 0.041, 0.112, 0.084, 0.372, 0.011, 0.105, 0.174, 0.026, 0.011, 0.13786213786213786, 0.14885114885114886, 0.016, 0.125, 0.245, 0.009]
min:
0.006993006993006993
max:
0.372
std:
0.09899663970441869
mean:
0.1225971555390717
median:
0.1085
95% confidence interval for the mean:
(0.08499926034990943,0.16019505072823398)

scenario 6 lift all lockdowns
using peak of time series:
stats on infected:
data: [0.164, 0.261, 0.175, 0.09, 0.204, 0.188, 0.2465069860279441, 0.186, 0.139, 0.006, 0.362, 0.321, 0.231, 0.062, 0.3, 0.015, 0.008, 0.036, 0.297, 0.105, 0.07470119521912351, 0.035, 0.081, 0.354, 0.014, 0.117, 0.017, 0.33, 0.23, 0.305]
min:
0.006
max:
0.362
std:
0.11504660977523183
mean:
0.1651402727082356
median:
0.16949999999999998
95% confidence interval for the mean:
(0.12144676564463626,0.20883377977183498)


scenario 7 
using peak of time series:
stats on infected:
data: [0.4195804195804196, 0.314, 0.258, 0.03090727816550349, 0.034, 0.283, 0.015, 0.039, 0.022, 0.463, 0.048, 0.142, 0.1998001998001998, 0.226, 0.329, 0.106, 0.214, 0.014, 0.02, 0.009, 0.179, 0.007, 0.291, 0.41, 0.005994005994005994, 0.25, 0.046, 0.177, 0.007, 0.245]
min:
0.005994005994005994
max:
0.463
std:
0.14035386421440843
mean:
0.16014273011800428
median:
0.15949999999999998
95% confidence interval for the mean:
(0.10683779075962621,0.21344766947638236)

**Comment by andre-senna** [comment]
This issue seems to be resolved as demonstrated in this notebook

http://127.0.0.1:8887/notebooks/BasicTestCase.ipynb
