### ISSUE TITLE
Even though agents accept invitations they do not end up in restaurants according to snapshot module

### ISSUE THREAD

**Issue by deborahduong** [singnet/covid-simulation#61]
https://github.com/deborahduong/covid-simulation/blob/deborah/covid19_sir/Simulation.ipynb
This notebooknhas the function that shows which building every agent is in, in a snapshot.  You can run it by setting debug to True in either CovidModel() or multiple_runs.  According to it, no one ever actually goes to the restaurant, when snapshots are taken at every step.  This is true even though all accept invitations when risk_tolerance is set to mean 1 stdev 0.

**Comment by deborahduong** [comment]
@andre-senna volunteered to debug this slack channel 8/19

**Comment by andre-senna** [comment]
Please put your test code in a branch and provide instructions to replicate the error you see.

**Comment by deborahduong** [comment]
https://github.com/deborahduong/covid-simulation/blob/master/covid19_sir/Simulation.ipynb
I made a pull request for this notebook because Matt has to take snapshots too.  (However, the parameter of how many cycles to print should be exposed in the notebook)  This notebook shows that if I print after every state of every day, none of the restaurants are occupied.  If printing after every state after every day doesnt show a snapshot of restaurants for some reason, please advise when a good time to print if restaurants have customers.  The pull request is also there because I had to debug the debugging statements , including the module for cycles, that it has to be after every state to capture restaurants and not just in the morning, that a spot debugging is needed in case these snapshots are taken after restaurants have cleared even though it is done after each of 7 states in the day.

**Comment by deborahduong** [comment]
(Instructions are just run the notebook, or look at the run in there already)

**Comment by deborahduong** [comment]
I modified the notebook in the pull request , by turning off debug = True, so it can download easily.  I also exposed the debug_every_n_cycles parameter so you can print every 1 cycle or every 20 from the notebook as you wish.  But if you put it on 1 now, you can see that  no restaurants have occupants as snapshots are taken after each of 7 states every day.

**Comment by deborahduong** [comment]
(Instructions are, set debug to true in instantiating the covid model, in the first scenario 1.  )

**Comment by andre-senna** [comment]
Hi @deborahduong  

The reason you don't see humans in the restaurants is because your printing code is printing only the number of humans in units and the human list in units. You are not printing the humans in the building itself.

It is working OK for buildings because they have offices or apartments which are building units. But for restaurants (which don't have units) this code doesn't work.

I added a branch https://github.com/singnet/covid-simulation/tree/senna-debug-2 with a debug code similar to yours but fixed to print Restaurants properly (debug code inside `base.py`)

```
        while not flag:
            logger().info(f"STATE: {self.current_state}")
            for agent in self.agents:
                if type(agent).__name__ == 'District':
                    print("{} District:".format(agent.name))
                    for i,building in enumerate(agent.locations):
                        num_humans_in_rooms = [len(room.humans) for room in building.locations]
                        print("{0}{1}".format(type(building).__name__, i))
                        print(num_humans_in_rooms)
                        humans_in_building = [human.unique_id for human in building.humans]
                        print(humans_in_building)
                    for i,building in enumerate(agent.locations):
                        for j,room in enumerate(building.locations):
                            humans_in_rooms = [human.unique_id for human in room.humans]
                            print("{0}{1}-room{2}".format(type(building).__name__, i,j))
                            print(humans_in_rooms)
            self.schedule.step()
            self.current_state = self.next_state[self.current_state]
            if self.current_state == SimulationState.MORNING_AT_HOME:
                flag = True
```

With this fix I see several outputs like this:

```
HomogeneousBuilding9
[7, 9, 8, 10, 9, 7, 10, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[]
Restaurant10
[]
['Adult71', 'Adult266', 'Adult521', 'Adult489', 'Adult199', 'Adult10', 'Adult191', 'Adult179', 'Adult193', 'Adult37', 'Adult376', 'Adult4', 'Adult899', 'Adult865', 'Adult224', 'Adult391', 'Adult432', 'Adult471', 'Adult11', 'Adult5', 'Adult90', 'Adult317', 'Adult162', 'Adult207', 'Adult87', 'Adult927', 'Adult99', 'Adult98', 'Adult596', 'Adult807', 'Adult303', 'Adult8', 'Adult138', 'Adult848', 'Adult957', 'Adult59', 'Adult738', 'Adult637', 'Adult35', 'Adult1', 'Adult226', 'Adult924', 'Adult203', 'Adult25']
```

To run this code just download the branch and run `python3 simple-simulation.py`

Now we also have a log file in `/tmp/simulation.log` where you can see lines like this:

```
...
INFO: human_797 decided to invite friends to a restaurant
INFO: STATE: SimulationState.COMMUTING_TO_POST_WORK_ACTIVITY
INFO: STATE: SimulationState.POST_WORK_ACTIVITY
INFO: Restaurant is spreading infection amongst 30 humans
INFO: Restaurant is spreading infection amongst 46 humans
INFO: Restaurant is spreading infection amongst 43 humans
INFO: Restaurant is spreading infection amongst 2 humans
INFO: STATE: SimulationState.COMMUTING_TO_HOME
...
```
