### ISSUE TITLE
Have a central location where simulation objects can be accessed for debugging purposes.

### ISSUE THREAD

**Issue by deborahduong** [singnet/covid-simulation#67]
Or if you do please tell me where it is.  It seems like the only location of districts is within agents, that have different subsets of districts.  If it does not exist, please create a central location that I can always access, to take a snapshot of the simulation at any time.  In a past issue I made Covid-Model this location, and saved districts there, but the pull request was rejected.

**Comment by deborahduong** [comment]
Or, if it goes better with your design, please tell me the best way to accomplish the same thing within your framework

**Comment by deborahduong** [comment]
Yes you did enable it to be printed out periodically as I did, in your framework, and that was very good.  But the difference I am asking for here is, how do I call it while debugging, get a picture at any time I need it, including between arbitrary lines of the program.

**Comment by andre-senna** [comment]
You can iterate through `agents` which is defined in `CovidModel`.

So you can either look for `debug` flag in each agent and call `_debug()` by hand or you can ask for agent's type and, for example, call `_print_district_rooms()` which is the debug printing function you wrote which I moved to `District` in ocations.py`.

**Comment by deborahduong** [comment]
Sorry, I misunderstood what you were said, but now I have it straight
